### ISSUE TITLE
GitHub Actions ワークフロー最適化

### ISSUE THREAD

**Issue by panicboat** [panicboat/monorepo#63]
# ⚡ GitHub Actions CI/CDワークフローの最適化

## 概要
CI/CDパイプラインの効率化とコスト削減を実現する。

## 背景
- ワークフロー実行時間が長い
- 不要な並列実行によるリソース浪費
- パス変更検出の精度向上が必要

## 実装内容
- [ ] `dorny/paths-filter`アクションの導入
- [ ] キャッシュ戦略の強化
  - [ ] Terraformプランキャッシュ
  - [ ] 依存関係キャッシュ（Go mod、npm、bundler）
- [ ] マトリックス戦略での並列化
- [ ] 不要なワークフロー実行の削減

## 受け入れ基準
- [ ] 変更されたサービスのみでCI/CD実行
- [ ] ワークフロー実行時間20%以上短縮
- [ ] キャッシュヒット率80%以上
- [ ] GitHub Actions使用量の削減

## 技術詳細
```yaml
# 例：パス変更検出
- uses: dorny/paths-filter@v2
  with:
    filters: |
      user-service:
        - 'user-service/**'
      payment-service:
        - 'payment-service/**'

**Comment by panicboat** [comment]
# GitHub Actions ワークフロー疎結合化プロジェクト

## プロジェクト概要

現在のmonorepo用GitHub Actionsワークフローを疎結合なアーキテクチャに再設計し、保守性と拡張性を向上させるプロジェクトです。

### 現在の課題

- `reusable--terragrunt-orchestrator.yaml`で差分検知とデプロイ実行が密結合
- 新しいサービス追加時の設定変更が複雑
- 手動でのデプロイ制御が困難

### 目標アーキテクチャ

差分検知とデプロイ実行を分離し、PRラベルを介した疎結合な仕組みを構築します。

```mermaid
graph LR
    A[PR作成/更新] --> B[差分検知ワークフロー]
    B --> C[ディレクトリ-ラベル定義参照]
    C --> D[PRラベル付与]
    D --> E[ラベル変更トリガー]
    E --> F[デプロイ実行ワークフロー]
    F --> G[既存のterragrunt-executor呼び出し]
```

## 実装する内容

### 1. ディレクトリ-ラベルマッピング定義ファイル

**ファイル**: `.github/directory-label-mapping.yaml`

monorepoの各ディレクトリ変更時に付与すべきPRラベルを定義します。

**主要な設計方針**:

- **シンプルスタート**: サービス単位の統一デプロイ（`deploy:service:environment`）
- **拡張性**: 将来的に技術スタック別制御（`deploy:service:environment:stack`）に対応可能
- **ブランチ戦略対応**: 現在の develop/staging/production ブランチ戦略に適合
- **設定統合**: 既存の`.github/terragrunt-actions-config.yaml`の機能も統合し、一元管理

**設定統合例**:

```yaml
# .github/directory-label-mapping.yaml
# 環境ごとの共通設定
environment_config:
  develop:
    aws_region: "ap-northeast-1"
    iam_role: "arn:aws:iam::559744160976:role/develop-github-actions-role"
    
  staging:
    aws_region: "ap-northeast-1"
    iam_role: "arn:aws:iam::123456789012:role/staging-github-actions-role"
    
  production:
    aws_region: "ap-northeast-1"
    iam_role: "arn:aws:iam::123456789012:role/production-github-actions-role"

# ディレクトリ構成規約（working_directory自動生成用）
directory_conventions:
  terragrunt: "{service}/terragrunt/envs/{environment}"
  kubernetes: "{service}/kubernetes/overlays/{environment}"

# 共通設定（デフォルト値）
defaults:
  terraform_version: "1.5.7"
  terragrunt_version: "0.53.2"
  kubectl_version: "1.28.0"
  kustomize_version: "5.0.0"

mappings:
  github-oidc-auth/terragrunt/envs/develop:
    labels:
      - "deploy:github-oidc-auth:develop"
    service: "github-oidc-auth"
    environment: "develop"
    stack: "terragrunt"
    # working_directory は規約から自動生成
    # 環境設定（IAMロール、リージョン）は environment_config から自動継承
    
  github-oidc-auth/kubernetes/overlays/develop:
    labels:
      - "deploy:github-oidc-auth:develop"
    service: "github-oidc-auth"
    environment: "develop"
    stack: "kubernetes"
    # namespace等の個別設定のみ記載
    namespace: "github-oidc-auth-develop"
```

**設定統合のメリット**:

- マッピング定義とデプロイ設定が一元管理される
- **環境ごとに統一されたIAMロール設定**
- **ディレクトリ構成規約による自動working_directory生成**
- サービス・環境ごとの設定が明確に分離される
- 新しいサービス追加時の設定が最小限

### 2. 差分検知・ラベル付与ワークフロー

**ファイル**: `.github/workflows/detect-changes-and-label.yaml`

**責務**:

- PR作成・更新時に変更されたファイルを検知
- マッピング定義ファイルを参照してラベルを決定
- 不要な古いラベルを削除し、必要なラベルを追加

**トリガー**:

- `pull_request` (types: `[opened, synchronize]`)

**主要処理**:

1. git diffで変更ファイルリストを取得
1. マッピング定義と照合してラベルを決定
1. GitHub APIでラベル管理（追加・削除）

### 3. ラベル変更トリガー・デプロイ実行ワークフロー

**ファイル**: `.github/workflows/terragrunt-deploy.yaml`

**責務**:

- ラベル変更時にデプロイ対象を特定
- 既存の`reusable--terragrunt-single-env.yaml`を呼び出してデプロイ実行

**トリガー**:

- `pull_request` (types: `[labeled, unlabeled]`) - plan実行
- `push` (branches: `[develop, staging/*, production/*]`) - apply実行

**主要処理**:

1. ラベル情報からサービス・環境情報を抽出
1. 既存のreusableワークフローに適切なパラメータを渡して実行

## 技術仕様

### ラベル命名規則

```yaml
# 基本形（Phase 1）
deploy:github-oidc-auth:develop
deploy:github-oidc-auth:staging
deploy:github-oidc-auth:production

# 拡張形（Phase 2 - 必要時のみ）
deploy:github-oidc-auth:develop:terragrunt
deploy:github-oidc-auth:develop:kubernetes
```

### monorepo構成の前提

```
monorepo/
├── github-oidc-auth/
│   ├── src/                    # アプリケーションコード
│   ├── terragrunt/            # インフラコード
│   │   └── envs/
│   │       ├── develop/
│   │       ├── staging/
│   │       └── production/
│   └── kubernetes/            # K8sマニフェスト
│       └── envs/
│           ├── develop/
│           ├── staging/
│           └── production/
└── .github/workflows/
```

### ブランチ戦略

```
develop                           # 開発環境への自動デプロイ
├── staging/github-oidc-auth     # github-oidc-authのstaging環境
├── staging/service-a            # service-aのstaging環境
├── production/github-oidc-auth  # github-oidc-authのproduction環境
└── production/service-a         # service-aのproduction環境
```

## 実装タスク

### タスク1: ディレクトリ-ラベルマッピング定義ファイル作成

**ファイル**: `.github/directory-label-mapping.yaml`

**要件**:

- github-oidc-authサービスの全環境（develop/staging/production）をサポート
- terragruntとkubernetesディレクトリの変更を同一ラベルにマッピング
- 将来の拡張（技術スタック別制御、新サービス追加）を考慮した構造
- ラベル色設定、クリーンアップ設定を含む
- 既存の`.github/terragrunt-actions-config.yaml`の設定内容を統合し、一元管理
- **環境ごとに統一されたIAMロール設定（develop/staging/production）**
- **ディレクトリ構成規約によるworking_directory自動生成**
  - terragrunt: `{service}/terragrunt/envs/{environment}`
  - kubernetes: `{service}/kubernetes/overlays/{environment}`
- defaults設定により共通項目（バージョン等）の重複を削減

### タスク2: 差分検知・ラベル付与ワークフロー実装

**ファイル**: `.github/workflows/detect-changes-and-label.yaml`

**要件**:

- PR作成・更新時のトリガー
- git diffによる変更ファイル検知
- YAML定義ファイルの読み込み・解析
- GitHub APIでのラベル管理（既存ラベル削除 + 新規ラベル追加）
- エラーハンドリング（定義ファイル不正、API呼び出し失敗等）

**技術的な注意点**:

- 既存の権限設定（GitHub App token）を活用
- `yq`コマンドでYAML解析
- ラベル作成時の色設定対応

### タスク3: ラベル変更トリガー・デプロイ実行ワークフロー実装

**ファイル**: `.github/workflows/terragrunt-deploy.yaml`

**要件**:

- ラベル変更（labeled/unlabeled）とpushイベントのトリガー
- ラベル名からサービス・環境・技術スタック情報の抽出
- 新しいアーキテクチャに最適化されたデプロイ実行（既存reusableワークフローの活用 or 新設計）
- 複数ラベルがある場合の並列実行制御

**技術的な注意点**:

- 既存のreusableワークフローのパラメータ形式に合わせる（または新設計で置き換え）
- エラー時の適切な通知
- terragruntの設定管理を新しいアーキテクチャに最適化

### タスク4: 既存ワークフローの段階的置き換え準備

**要件**:

- 既存の`github-oidc-auth--ci.yaml`との共存期間を考慮
- 新旧ワークフローの重複実行防止措置
- 新ワークフローの動作確認用のテスト手順

## 期待される効果

### 保守性の向上

- 各ワークフローが単一責任を持つため、修正が局所化
- 新しいサービス追加時はマッピング定義ファイルの更新のみ

### 運用性の向上

- PRラベルによる視覚的なデプロイ対象確認
- 手動ラベル操作による柔軟なデプロイ制御

### 拡張性の向上

- 技術スタック別の詳細制御への対応
- 新しいデプロイ対象（DB migration等）の追加が容易

## 実装時の注意事項

### セキュリティ

- 既存のGitHub App権限設定を維持
- production環境への誤デプロイ防止措置

### パフォーマンス

- 大量のファイル変更時の差分検知性能
- 並列実行時のAPI rate limit考慮

### 互換性

- 新しいアーキテクチャに最適化されたterragrunt設定設計
- 既存のPRコメント機能の継続

### 実装時のポイント

#### 1. working_directory自動生成ロジック

```javascript
// ディレクトリ構成規約に基づく自動生成
function generateWorkingDirectory(service, environment, stack) {
  const convention = directory_conventions[stack];
  return convention
    .replace('{service}', service)
    .replace('{environment}', environment);
}

// 例:
// generateWorkingDirectory('github-oidc-auth', 'develop', 'terragrunt')
// → 'github-oidc-auth/terragrunt/envs/develop'
// generateWorkingDirectory('github-oidc-auth', 'develop', 'kubernetes') 
// → 'github-oidc-auth/kubernetes/overlays/develop'
```

#### 2. 環境設定継承ロジック

```javascript
// environment_configから設定を自動継承
function getEnvironmentConfig(environment) {
  return environment_config[environment];
}

// デフォルト設定とのマージ
function getMergedConfig(mappingConfig, environment) {
  const envConfig = getEnvironmentConfig(environment);
  const defaultConfig = defaults;
  
  return {
    ...defaultConfig,
    ...envConfig,
    ...mappingConfig  // 個別設定で上書き
  };
}
```

#### 3. ラベル解析ロジック

```javascript
// ラベル名からサービス・環境・スタック情報を抽出
function parseDeployLabel(labelName) {
  // 形式: deploy:service:environment[:stack]
  const match = labelName.match(/^deploy:([^:]+):([^:]+)(?::([^:]+))?$/);
  if (!match) return null;
  
  return {
    service: match[1],
    environment: match[2],
    stack: match[3] || null  // 省略時はnull
  };
}
```

#### 4. YAML設定ファイル読み込み

```bash
# yqコマンドを使用した設定値取得例
SERVICE=$(yq e ".mappings[\"$CHANGED_PATH\"].service" .github/directory-label-mapping.yaml)
ENVIRONMENT=$(yq e ".mappings[\"$CHANGED_PATH\"].environment" .github/directory-label-mapping.yaml)
STACK=$(yq e ".mappings[\"$CHANGED_PATH\"].stack" .github/directory-label-mapping.yaml)

# 環境設定の取得
IAM_ROLE=$(yq e ".environment_config.$ENVIRONMENT.iam_role" .github/directory-label-mapping.yaml)
AWS_REGION=$(yq e ".environment_config.$ENVIRONMENT.aws_region" .github/directory-label-mapping.yaml)

# デフォルト設定の取得
TERRAFORM_VERSION=$(yq e ".defaults.terraform_version" .github/directory-label-mapping.yaml)
```

## テスト戦略

### 単体テスト

- マッピング定義ファイルの解析ロジック
- ラベル名の解析・抽出ロジック

### 統合テスト

- 実際のPRでの差分検知からデプロイまでの一連の流れ
- 複数環境の同時変更時の動作

### 運用テスト

- 手動ラベル操作時の動作
- エラー時の復旧手順

このREADMEを参考に、段階的な実装を進めてください。不明な点があれば、既存コードの`.github/workflows/`ディレクトリを参照し、現在の実装パターンに合わせて実装してください。
